
spring.profiles.active=dev

spring.application.name=es-auth-ms

server.servlet.context-path=/easyschool/auth

# SERVEUR EUREKA
eureka.instance.home-page-url-path=${server.servlet.context-path}/
eureka.instance.status-page-url-path=${server.servlet.context-path}/actuator/info
eureka.instance.health-check-url-path=${server.servlet.context-path}/actuator/health


spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.defer-datasource-initialization=false

spring.jpa.show-sql=true

# Configuration pour envoi email 
spring.mail.host=${EMAIL_SERVER}
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_SENDER_USERNAME}
spring.mail.password=${EMAIL_SENDER_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# SECRET KEY POUR JWT
jwt.secret-key =${JWT_SECRET_KEY}


# internationalisation
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# accepter les references circulaires
spring.main.allow-circular-references=true