# Configuration pour la base de donnees en developpement 

server.port=${SERVER_PORT}

eureka.client.service-url.defaultZone=http://localhost:8091/eureka/

spring.datasource.url=jdbc:postgresql://localhost:5432/es_authentication_db
spring.datasource.username=postgres
spring.datasource.password=sojez

spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG

spring.security.user.name=admin
spring.security.user.password=admin123